name: Release Protobuf Files

on:
  push:
    tags:
      - 'v*' # Triggers workflow on tags like v1.0, v1.0.1, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Protobuf Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(find . -name "*.proto"); do
            echo "Uploading $file"
            gh release upload ${{ github.ref_name }} "$file" --clobber
          done
